baseURL = "https://www.bantel-stiftung.de/"
languageCode = "de-DE"
title = "Dr.-Egon-Bantel-Stiftung"
theme = "dimension"
defaultContentLanguage = "de"
enableRobotsTXT = true
disableKinds=["RSS"]

RelativeURLs=true
CanonifyURLs=true

[params]
description = '<!--[-->Treuhandstiftung des GGAP e.V.<!--]--><br /><!--[-->Bildung, Nachhaltigkeit, Gerechtigkeit für die Armen dieser Welt.<!--]-->'
logo = ""
copyright = "2018 GGAP e.V"
